on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Restore dependencies
        run: dotnet restore src/TechFood.Api/TechFood.Api.csproj
      - name: Build
        run: dotnet build --configuration Release src/TechFood.Api/TechFood.Api.csproj
      - name: Test
        run: dotnet test
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/techfood-api:latest -f src/TechFood.Api/Dockerfile .
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/techfood-api:latest

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Publish (simulado)
        run: echo "Publicação de artefato .NET (ajuste conforme necessário)"
