jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore src/TechFood.Api/TechFood.Api.csproj
      - name: Build
        run: dotnet build --configuration Release src/TechFood.Api/TechFood.Api.csproj
      - name: Test
        run: dotnet test --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Publish (simulado)
        run: echo "Publicação de artefato .NET (ajuste conforme necessário)"

  deploy-STG:
    runs-on: ubuntu-latest
    environment:
      name: stg
    needs: publish
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy
        shell: bash
        run: echo "Deploy STG .NET (ajuste conforme necessário)"

  deploy-PRE:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    environment:
      name: pre
    needs: publish
    steps:
      - name: Deploy
        shell: bash
        run: echo "Deploy PRE .NET (ajuste conforme necessário)"

  deploy-PRD:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: prd
    needs: publish
    steps:
      - name: Deploy
        shell: bash
        run: echo "Deploy PRD .NET (ajuste conforme necessário)"
